# Generated by Django 3.1 on 2022-12-21 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Страница о приложении',
                'verbose_name_plural': 'Страница о приложении',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Контент')),
                ('postDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации')),
                ('articleCover', models.CharField(max_length=500, verbose_name='Ссылка на изображение (1280x720)')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='LoanItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeName', models.CharField(max_length=255, verbose_name='Наименование места')),
                ('smallDescription', models.TextField(verbose_name='Описание')),
                ('whatsapp', models.CharField(blank=True, max_length=500, null=True, verbose_name='WhatsApp')),
                ('instagram', models.CharField(blank=True, max_length=500, null=True, verbose_name='Instagram')),
                ('map', models.CharField(blank=True, max_length=500, null=True, verbose_name='Карта')),
            ],
            options={
                'verbose_name': 'Аренда',
                'verbose_name_plural': 'Аренда',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourName', models.CharField(max_length=255, verbose_name='Наименование тура')),
                ('description', models.TextField(verbose_name='Описание')),
                ('postDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации')),
                ('tourDateStart', models.DateField(verbose_name='Начало')),
                ('tourDateEnd', models.DateField(verbose_name='Конец')),
                ('tourCover', models.CharField(max_length=500, verbose_name='Ссылка на изображение (1280x720)')),
                ('whatsapp', models.CharField(blank=True, max_length=500, null=True, verbose_name='WhatsApp')),
                ('instagram', models.CharField(blank=True, max_length=500, null=True, verbose_name='Instagram')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
            },
        ),
    ]
