# Generated by Django 3.1 on 2022-12-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Цена тура'),
        ),
    ]
