# Generated by Django 3.1 on 2022-12-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0002_tour_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
