# Generated by Django 3.1 on 2022-12-26 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0003_auto_20221226_0705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campingName', models.CharField(max_length=255, verbose_name='Наименование тура')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.FloatField(default=0.0, verbose_name='Цена тура')),
                ('postDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации')),
                ('tourDateStart', models.DateField(verbose_name='Начало')),
                ('tourDateEnd', models.DateField(verbose_name='Конец')),
                ('tourCover', models.CharField(max_length=500, verbose_name='Ссылка на изображение (1280x720)')),
                ('whatsapp', models.CharField(blank=True, max_length=500, null=True, verbose_name='WhatsApp')),
                ('instagram', models.CharField(blank=True, max_length=500, null=True, verbose_name='Instagram')),
            ],
            options={
                'verbose_name': 'Кемпинг',
                'verbose_name_plural': 'Кемпинг',
            },
        ),
    ]
