# Generated by Django 3.1 on 2023-01-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0004_camping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('museumName', models.CharField(max_length=255, verbose_name='Наименование музея')),
                ('mapLink', models.CharField(max_length=500, verbose_name='Ссылка на карту')),
            ],
            options={
                'verbose_name': 'Музей',
                'verbose_name_plural': 'Музеи',
            },
        ),
    ]
